update installers' check for existing Centmin Mod installs in 130.00beta01
- Prevent users re-running the initial Centmin Mod installer on existing Centmin Mod installations. There was a check but it occurred later into the routine which prevents messing up existing install but it still created install log files that the initially installer reads and makes incorrect initial install time reported calculations given users impression that Centmin Mod was reinstalled. when in fact, the install aborted but still reported install times. This update moves the check way earlier during installer's run to abort sooner with a more appropriate message like:

error: Detected that Centmin Mod has already been installed on this system
       You are only meant to run initial installer once
       If you want to reinstall Centmin Mod, you need to reinstall
       your operating system first.