fix AlmaLinux <8.7 GPG key changes in 130.00beta01
- AlmaLinux <-8.7 GPG key is outdated due to AlmaLinux 8.8+ GPG key changes https://almalinux.org/blog/2023-12-20-almalinux-8-key-update/. This update to Centmin Mod 130.00beta01 installers attempts to detect older AlmaLinux <=8.7 and install updated GPG keys. Users might run into this issue if web host provides an out of box older AlmaLinux <=8.7 image. If you try yum update or yum install of packages on AlmaLinux <=8.7 you may get error messages like

Public key for unbound-libs-1.16.2-5.el8_9.6.x86_64.rpm is not installed. Failing package is: unbound-libs-1.16.2-5.el8_9.6.x86_64
GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED

The manual fix is to install AlmaLinux's 8.8+ GPG keys via command:

rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux

This update is to auto run this command if AlmaLinux <=8.7 is detected