part 2 update PHP-FPM routine for PHP 8.3.16+ on CentOS 7 systems in 140.00beta01
- PHP 8.3.16 introduced code changes for FFI ext/ffi/ffi.c are incompatible with end of life CentOS 7's glibc 2.17 version causing PHP 8.3.16+ PHP-FPM compilations to fail on CentOS 7 (el7) operating systems. AlmaLinux or Rocky Linux el8 and el9 systems are okay as they use newer glibc versions.
- This update improves previous January 20, 2025 patch fix routine and applies a workaround patch to allow PHP 8.3.16+ to compile properly on EOL CentOS 7 systems as PHP has stated they will not update PHP to work with now end of life CentOS 7 systems
- existing users can run cmupdate command before running centmin.sh menu option 5 to compile/update PHP 8.3.16+

example error message:

php-8.3.16/ext/ffi/ffi.c:5047:45: error: macro "strncmp" requires 3 arguments, but only 2 given
if (strncmp(code_pos, ZEND_STRL("#define")) == 0) {

or

php-8.3.19/ext/ffi/ffi.c:5047:45: error: macro "strncmp" requires 3 arguments, but only 2 given
 5047 |   if (strncmp(code_pos, ZEND_STRL("#define")) == 0) {