downgrade back to nginx lua module 0.9.20
0.10.0 has an error during nginx compilation

[CODE]
ccache /usr/bin/clang -ferror-limit=0 -c -I/usr/local/include/luajit-2.1  -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g -m64 -mtune=native -mfpmath=sse -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-sign-compare -Wno-string-plus-int -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion  -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/chromium/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/google-sparsehash/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/protobuf/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/re2/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/out/Release/obj/gen -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/apr/src/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/aprutil/src/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I ../ngx_devel_kit-0.2.19/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.1 -I ../lua-nginx-module-0.10.0/src/api -I ../nginx_upstream_check_module-0.3.0 -I ../pcre-8.38 -I ../libressl-2.2.5/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.2.19/src -I src/mail -I src/stream \
                -o objs/addon/src/ngx_http_lua_module.o \
                ../lua-nginx-module-0.10.0/src/ngx_http_lua_module.c
../lua-nginx-module-0.10.0/src/ngx_http_lua_module.c:897:9: error: implicit declaration of function 'SSL_CTX_set_cert_cb' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        SSL_CTX_set_cert_cb(sscf->ssl.ctx, ngx_http_lua_ssl_cert_handler, NULL);
        ^
1 error generated.
make[1]: *** [objs/addon/src/ngx_http_lua_module.o] Error 1
make[1]: Leaving directory `/svr-setup/nginx-1.9.9'
make: *** [install] Error 2
[/CODE]